#filename: query-026.rq
PREFIX dbpedia-ont: <http://dbpedia.org/ontology/>
SELECT * 
WHERE {
{
	?s dbpedia-ont:meshId "D001924"^^xsd:string .
	?s dbpedia-ont:abstract ?abstract .
	?s rdfs:comment ?comment .
	FILTER ( langMatches(lang(?abstract),"en" ))
	FILTER ( langMatches(lang(?comment),"en" ))
}
UNION
{
	?s dbpedia-ont:abstract ?abstract .
	?s rdf:type foaf:Person .
	FILTER ( langMatches(lang(?abstract),"en" ))
	FILTER (regex(?abstract, "Concussion","i"))
	FILTER (CONTAINS(?abstract,"children"))
}
} 
ORDER BY ?s
LIMIT 100
