#filename: query-023.rq
PREFIX dbpedia-ont: <http://dbpedia.org/ontology/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
SELECT * 
WHERE {
{
	?s dbpedia-ont:meshId "D001924"^^xsd:string .
	?s dbpedia-ont:abstract ?abstract .
	?s rdfs:comment ?comment .
	FILTER ( langMatches(lang(?abstract),"en" ))
	FILTER ( langMatches(lang(?comment),"en" ))
}
UNION
{
	?s dbpedia-ont:abstract ?abstract .
	?s rdf:type foaf:Person .
	?s dbpedia2:dateOfBirth ?year
	FILTER ( langMatches(lang(?abstract),"en" ))
	FILTER (regex(?abstract, "Concussion","i"))
}
}
ORDER BY ?year ?s
LIMIT 100
