#filename: query-006-style2.rq
PREFIX books: <http://example.org/ns/book#>
PREFIX schema: <http://schema.org/>
SELECT ?propertyName ?propertyValue
WHERE 
{ 
?bookID schema:name "Linked data evolving the web into a global data space" ;
 		schema:datePublished "2011" ;
      	?propertyName ?propertyValue .
}
