#filename: query-029.rq

PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT ?city ?country

WHERE {

?subject dbpedia-owl:city ?city .
?subject dbpedia-owl:country ?country .

FILTER (?country IN (<http://dbpedia.org/resource/Canada>, <http://dbpedia.org/resource/United_States>))
}