#filename: query-030.rq

PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?city <http://dbpedia.org/resource/United_States> ?state

WHERE {

?subject dbpedia-owl:city ?city .
?subject dbpedia-owl:country <http://dbpedia.org/resource/United_States> .
?city <http://dbpedia.org/ontology/isPartOf> ?state .

FILTER (?state NOT IN (<http://dbpedia.org/resource/New_Jersey>,<http://dbpedia.org/resource/New_York>))
}