#filename: query-027.rq

PREFIX books: <http://example.org/ns/book#>
PREFIX schema: <http://schema.org/>
PREFIX db: <http://dbpedia.org/resource/>

SELECT ?bookID ?name ?location ?copies
WHERE 
{ 
	?bookID schema:name ?name .
	?bookID books:copies ?copies .
	?bookID books:location ?location .
	FILTER (?copies >= 25 ) .
}