#filename: query-028.rq

PREFIX books: <http://example.org/ns/book#>
PREFIX schema: <http://schema.org/>

SELECT ?bookID ?name ?location ?copies
WHERE 
{ 
	?bookID schema:name ?name .
	?bookID books:copies ?copies .
	?bookID books:location ?location .
	FILTER (?location IN (<http://dbpedia.org/resource/Montreal>, <http://dbpedia.org/resource/Boston>)) .
}

