#filename: query-033.rq

PREFIX books: <http://example.org/ns/book#>
PREFIX schema: <http://schema.org/>
PREFIX db: <http://dbpedia.org/resource/>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT ?bookID ?name ?doi ?format
WHERE 
{ 
?bookID 
schema:name ?name ;
OPTIONAL { ?bookID books:doi ?doi } .
OPTIONAL { ?bookID dc:format ?format }
}