#!/bin/sh
#
# Contain Environment variables for installs
#

HOME_DIR="/home/vagrant"

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

JENA_VERSION=3.0.1
JENA_BASE="$SHARED_DIR/jena"
if [ ! -d $JENA_BASE ]; then
  mkdir $JENA_BASE
fi


FUSEKI_VERSION=1.3.1
FUSEKI_HOME=/usr/share/fuseki
# Fuseki 2.x
# FUSEKI_VERSION=2.3.1
# FUSEKI_BASE=/etc/fuseki
# FUSEKI_DEPLOY=/var/lib/tomcat7/webapps
