#query-061.rq
	@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
	@prefix cat: <http://dbpedia.org/resource/Category:> .
	@prefix foaf: <http://xmlns.com/foaf/0.1/> .
	@prefix term: <http://example.org/medicalterms/> .
	@prefix dbprop: <http://dbpedia.org/ontology/> .
	@prefix owl: <http://www.w3.org/2002/07/owl#> .
	@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
	@prefix mads: <http://www.loc.gov/mads/rdf/v1#> .
	term:concutere rdfs:type "concussion_ontology" ;
                   term:meshid "D001924" ;
                   term:variant "Cerebral concussion"@en , "Concussion"@en , "Concussion of the brain"@en , "Brain--Concussion"@en ;
                   owl:sameAs <http://id.loc.gov/authorities/subjects/sh85016330> .
